apps/urls.py
from django.urls import include, path
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('books_fbv_user/', include('books_fbv_user.urls', namespace='books_fbv_user')),
]

books_fbv_user/urls.py
from django.urls import path
from . import views

app_name = 'books_fbv_user'

urlpatterns = [
  path('', views.book_list, name='book_list'),
  path('new', views.book_create, name='book_new'),
  path('edit/<int:pk>', views.book_update, name='book_edit'),
  path('delete/<int:pk>', views.book_delete, name='book_delete'),
]

books_fbv_user/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

class Book(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    isbn = models.CharField(max_length=200)
    pages = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books_fbv_user:book_edit', kwargs={'pk': self.pk})

apps/views.py
from django.shortcuts import render

books_fbv_user/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm
from django import forms

from books_fbv_user.models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'pages', 'author', 'isbn']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'input'}),
            'pages': forms.TextInput(attrs={'class': 'input'}),
            'author': forms.TextInput(attrs={'class': 'input'}),
            'isbn': forms.TextInput(attrs={'class': 'input'}),
        }

@login_required
def book_list(request, template_name='books_fbv_user/book_list.html'):
    data = {}
    book = None
    query = request.GET.get('q')

    if query:
        if Book.objects.filter(name=query).exists():
            book = Book.objects.filter(name=query)
        data['object_list'] = book
        return render(request, template_name, data)

    if request.user.is_superuser:
        book = Book.objects.all()
    else:
        book = Book.objects.filter(user=request.user)
    data['object_list'] = book
    return render(request, template_name, data)

@login_required
def book_create(request, template_name='books_fbv_user/book_form.html'):
    form = BookForm(request.POST or None)
    if form.is_valid():
        book = form.save(commit=False)
        book.user = request.user
        book.save()
        return redirect('books_fbv_user:book_list')
    return render(request, template_name, {'form':form})

@login_required
def book_update(request, pk, template_name='books_fbv_user/book_form.html'):
    if request.user.is_superuser:
        book= get_object_or_404(Book, pk=pk)
    else:
        book= get_object_or_404(Book, pk=pk, user=request.user)
    form = BookForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        return redirect('books_fbv_user:book_list')
    return render(request, template_name, {'form':form})

@login_required
def book_delete(request, pk, template_name='books_fbv_user/book_confirm_delete.html'):
    if request.user.is_superuser:
        book= get_object_or_404(Book, pk=pk)
    else:
        book= get_object_or_404(Book, pk=pk, user=request.user)
    if request.method=='POST':
        book.delete()
        return redirect('books_fbv_user:book_list')
    return render(request, template_name, {'object':book})

books_fbv_user/templates/books_fbv_user/book_confirm_delete.html
{% block content %}
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}

* {box-sizing: border-box;}

body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.topnav {
  overflow: hidden;
  background-color: #e9e9e9;
}

.topnav a {
  float: left;
  display: block;
  color: black;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #2196F3;
  color: white;
}

.topnav .search-container {
  float: right;
}

.topnav input[type=text] {
  padding: 6px;
  margin-top: 8px;
  font-size: 17px;
  border: none;
}

.topnav .search-container button {
  float: right;
  padding: 6px 10px;
  margin-top: 8px;
  margin-right: 16px;
  background: #ddd;
  font-size: 17px;
  border: none;
  cursor: pointer;
}

.topnav .search-container button:hover {
  background: #ccc;
}

@media screen and (max-width: 600px) {
  .topnav .search-container {
    float: none;
  }
  .topnav a, .topnav input[type=text], .topnav .search-container button {
    float: none;
    display: block;
    text-align: left;
    width: 100%;
    margin: 0;
    padding: 14px;
  }
  .topnav input[type=text] {
    border: 1px solid #ccc;  
  }
}
</style>


<div class="topnav">
  <a class="active" href="{% url 'books_fbv_user:book_list' %}">Books List</a>
  <a href="{% url 'books_fbv_user:book_new' %}"> Add New Book</a>
  <div class="search-container">
    <form method="GET" action="" id="searchform">
      <input type="text" id="searchbox" name="q" value="{{ request.GET.q }}"placeholder="Search.." name="search">
      <button type="submit"><i class="fa fa-search"></i></button>
    </form>
  </div>
</div>
<h2><a href="{% url 'books_fbv_user:book_list' %}">Books FBV User</a>: Delete?</h2>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?<br/>
    <input type="submit" value="Delete" />
</form>

{% endblock %}

books_fbv_user/templates/books_fbv_user/book_form.html
{% block content %}
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}

* {box-sizing: border-box;}

body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.topnav {
  overflow: hidden;
  background-color: #e9e9e9;
}

.topnav a {
  float: left;
  display: block;
  color: black;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #2196F3;
  color: white;
}

.topnav .search-container {
  float: right;
}

.topnav input[type=text] {
  padding: 6px;
  margin-top: 8px;
  font-size: 17px;
  border: none;
}

.topnav .search-container button {
  float: right;
  padding: 6px 10px;
  margin-top: 8px;
  margin-right: 16px;
  background: #ddd;
  font-size: 17px;
  border: none;
  cursor: pointer;
}

.topnav .search-container button:hover {
  background: #ccc;
}

@media screen and (max-width: 600px) {
  .topnav .search-container {
    float: none;
  }
  .topnav a, .topnav input[type=text], .topnav .search-container button {
    float: none;
    display: block;
    text-align: left;
    width: 100%;
    margin: 0;
    padding: 14px;
  }
  .topnav input[type=text] {
    border: 1px solid #ccc;  
  }
}
</style>


<div class="topnav">
  <a class="active" href="{% url 'books_fbv_user:book_list' %}">Books List</a>
  <a href="{% url 'books_fbv_user:book_new' %}"> Add New Book</a>
  <div class="search-container">
    <form method="GET" action="" id="searchform">
      <input type="text" id="searchbox" name="q" value="{{ request.GET.q }}"placeholder="Search.." name="search">
      <button type="submit"><i class="fa fa-search"></i></button>
    </form>
  </div>
</div>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

books_fbv_user/templates/books_fbv_user/book_list.html
{% block content %}

<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}

* {box-sizing: border-box;}

body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.topnav {
  overflow: hidden;
  background-color: #e9e9e9;
}

.topnav a {
  float: left;
  display: block;
  color: black;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #2196F3;
  color: white;
}

.topnav .search-container {
  float: right;
}

.topnav input[type=text] {
  padding: 6px;
  margin-top: 8px;
  font-size: 17px;
  border: none;
}

.topnav .search-container button {
  float: right;
  padding: 6px 10px;
  margin-top: 8px;
  margin-right: 16px;
  background: #ddd;
  font-size: 17px;
  border: none;
  cursor: pointer;
}

.topnav .search-container button:hover {
  background: #ccc;
}

@media screen and (max-width: 600px) {
  .topnav .search-container {
    float: none;
  }
  .topnav a, .topnav input[type=text], .topnav .search-container button {
    float: none;
    display: block;
    text-align: left;
    width: 100%;
    margin: 0;
    padding: 14px;
  }
  .topnav input[type=text] {
    border: 1px solid #ccc;  
  }
}
</style>


<div class="topnav">
  <a class="active" href="{% url 'books_fbv_user:book_list' %}">Books List</a>
  <a href="{% url 'books_fbv_user:book_new' %}"> Add New Book</a>
  <div class="search-container">
    <form method="GET" action="" id="searchform">
      <input type="text" id="searchbox" name="q" value="{{ request.GET.q }}"placeholder="Search.." name="search">
      <button type="submit"><i class="fa fa-search"></i></button>
    </form>
  </div>
</div>




<h2>Books Table</h2>

<table>
  <tr>
    <th>Name</th>
    <th>Author</th>
    <th>Pages</th>
    <th>ISBN</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  

  {% for book in object_list %}
  <tr>
    <td>{{ book.name }}</td>
    <td>{{ book.author }}</td>
    <td>{{ book.pages }}</td>
    <td>{{ book.isbn }}</td>
    <td><a href="{% url 'books_fbv_user:book_edit' book.id %}">edit</a></td>
    <td><a href="{% url 'books_fbv_user:book_delete' book.id %}">delete</a></td>
    </tr>
  {% endfor %}

   
  
 
</table>



{% endblock %}